"""
Common constants for mainapp
"""
CSS_CLASS_SEPARATOR = " "

# ==================================================
# BOOTSTRAP COLUMN SIZE(CSS class)
# ==================================================
# Prefixes for each device
CSS_SMARTPHONE_COL_PREFIX = "col-"
CSS_TABLET_COL_PREFIX = "col-sm-"
CSS_DESKTOP_COL_PREFIX = "col-lg-"

# Smartphone sizes
# CSS_SMARTPHONE_COL_1 = CSS_SMARTPHONE_COL_PREFIX + "1"
# CSS_SMARTPHONE_COL_2 = CSS_SMARTPHONE_COL_PREFIX + "2"
# CSS_SMARTPHONE_COL_3 = CSS_SMARTPHONE_COL_PREFIX + "3"
# CSS_SMARTPHONE_COL_4 = CSS_SMARTPHONE_COL_PREFIX + "4"
# CSS_SMARTPHONE_COL_5 = CSS_SMARTPHONE_COL_PREFIX + "5"
# CSS_SMARTPHONE_COL_6 = CSS_SMARTPHONE_COL_PREFIX + "6"
# CSS_SMARTPHONE_COL_7 = CSS_SMARTPHONE_COL_PREFIX + "7"
# CSS_SMARTPHONE_COL_8 = CSS_SMARTPHONE_COL_PREFIX + "8"
# CSS_SMARTPHONE_COL_9 = CSS_SMARTPHONE_COL_PREFIX + "9"
# CSS_SMARTPHONE_COL_10 = CSS_SMARTPHONE_COL_PREFIX + "10"
# CSS_SMARTPHONE_COL_11 = CSS_SMARTPHONE_COL_PREFIX + "11"
CSS_SMARTPHONE_COL_12 = CSS_SMARTPHONE_COL_PREFIX + "12"

# Tablet sizes
# CSS_TABLET_COL_1 = CSS_TABLET_COL_PREFIX + "1"
# CSS_TABLET_COL_2 = CSS_TABLET_COL_PREFIX + "2"
# CSS_TABLET_COL_3 = CSS_TABLET_COL_PREFIX + "3"
CSS_TABLET_COL_4 = CSS_TABLET_COL_PREFIX + "4"
CSS_TABLET_COL_5 = CSS_TABLET_COL_PREFIX + "5"
CSS_TABLET_COL_6 = CSS_TABLET_COL_PREFIX + "6"
# CSS_TABLET_COL_7 = CSS_TABLET_COL_PREFIX + "7"
CSS_TABLET_COL_8 = CSS_TABLET_COL_PREFIX + "8"
# CSS_TABLET_COL_9 = CSS_TABLET_COL_PREFIX + "9"
# CSS_TABLET_COL_10 = CSS_TABLET_COL_PREFIX + "10"
# CSS_TABLET_COL_11 = CSS_TABLET_COL_PREFIX + "11"
# CSS_TABLET_COL_12 = CSS_TABLET_COL_PREFIX + "12"

# Desktop sizes
CSS_DESKTOP_COL_1 = CSS_DESKTOP_COL_PREFIX + "1"
CSS_DESKTOP_COL_2 = CSS_DESKTOP_COL_PREFIX + "2"
CSS_DESKTOP_COL_3 = CSS_DESKTOP_COL_PREFIX + "3"
CSS_DESKTOP_COL_4 = CSS_DESKTOP_COL_PREFIX + "4"
CSS_DESKTOP_COL_5 = CSS_DESKTOP_COL_PREFIX + "5"
CSS_DESKTOP_COL_6 = CSS_DESKTOP_COL_PREFIX + "6"
# CSS_DESKTOP_COL_7 = CSS_DESKTOP_COL_PREFIX + "7"
# CSS_DESKTOP_COL_8 = CSS_DESKTOP_COL_PREFIX + "8"
# CSS_DESKTOP_COL_9 = CSS_DESKTOP_COL_PREFIX + "9"
# CSS_DESKTOP_COL_10 = CSS_DESKTOP_COL_PREFIX + "10"
# CSS_DESKTOP_COL_11 = CSS_DESKTOP_COL_PREFIX + "11"
# CSS_DESKTOP_COL_12 = CSS_DESKTOP_COL_PREFIX + "12"

# All same size
# (smartphone: max(12), tablet: default(same as smartphone), desktop: default(same as tablet))
CSS_ALL_COL_MAX_12 = CSS_SMARTPHONE_COL_12

# ==================================================
