# ==================================================
# DB CONSTANTS for main app 
# (Generated by 'python manage.py create_db_const_file' command on 06/18/2023 16:17:00)
# ==================================================
TOWN_CITY_BOROUGH_NAME_LONDON_OPTION_LIST = [
]

STATION_LONDON_OPTION_LIST = [
]

# ==================================================
