# Generated by Django 4.1.3 on 2023-06-18 15:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TownCityBoroughNameLondon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('del_flg', models.BooleanField(default=False, verbose_name='Deleted Flg')),
                ('record_updated_at', models.DateTimeField(auto_now=True, verbose_name='Record Updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='town_city_borough_name_london_option_list_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created User (ID)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='town_city_borough_name_london_option_list_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted User (ID)')),
                ('record_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='town_city_borough_name_london_option_list_record_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Record Updated User (ID)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='town_city_borough_name_london_option_list_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated User (ID)')),
            ],
        ),
        migrations.CreateModel(
            name='StationLondon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=6)),
                ('value', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('del_flg', models.BooleanField(default=False, verbose_name='Deleted Flg')),
                ('record_updated_at', models.DateTimeField(auto_now=True, verbose_name='Record Updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='station_london_option_list_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created User (ID)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='station_london_option_list_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted User (ID)')),
                ('record_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='station_london_option_list_record_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Record Updated User (ID)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='station_london_option_list_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated User (ID)')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_happened_date', models.DateField(verbose_name='Problem Happened Date')),
                ('postcode', models.CharField(help_text='Enter capital alphabets or numbers without space.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter capital alphabets or numbers without space.', regex='^([A-Z0-9]{5,7})$')], verbose_name='Postcode')),
                ('nearest_station', models.CharField(max_length=6, verbose_name='Nearest Station')),
                ('address_line', models.CharField(max_length=200, verbose_name='Address Line')),
                ('county', models.CharField(default='Greater London', max_length=20, verbose_name='County')),
                ('problem_type', models.CharField(choices=[('01', 'Noise'), ('02', 'Hygiene'), ('03', 'Boundary Invasion'), ('04', 'Harassment'), ('05', 'Crime'), ('99', 'Other')], max_length=2, verbose_name='Problem Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('detail', models.TextField(max_length=1000, verbose_name='Detail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('del_flg', models.BooleanField(default=False, verbose_name='Deleted Flg')),
                ('record_updated_at', models.DateTimeField(auto_now=True, verbose_name='Record Updated at')),
                ('test_flg', models.BooleanField(default=False, verbose_name='Test Flg')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created User (ID)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted User (ID)')),
                ('record_updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_record_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Record Updated User (ID)')),
                ('town_city_borough_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporttown_city_borough_name_london_option_list', to='mainapp.towncityboroughnamelondon', verbose_name='Town/City/Borough Name')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated User (ID)')),
            ],
        ),
    ]
